basePath: /
definitions:
  controller.JamKerja:
    properties:
      durasi:
        example: 8
        type: integer
      gmt:
        example: 7
        type: integer
      hari:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jam_keluar:
        example: "16:00"
        type: string
      jam_masuk:
        example: "08:00"
        type: string
      piket_tim:
        example: Piket Z
        type: string
      shift:
        example: 2
        type: integer
    type: object
  controller.Karyawan:
    properties:
      hari_kerja:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jabatan:
        example: Anonymous
        type: string
      jam_kerja:
        items:
          $ref: '#/definitions/controller.JamKerja'
        type: array
      nama:
        description: ID          primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: Tes Swagger
        type: string
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Kuesioner:
    properties:
      biodata:
        $ref: '#/definitions/controller.Responden'
      email:
        example: jasmine@gmail.com
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: 123.11
        type: number
      status:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: Done
        type: string
    type: object
  controller.Presensi:
    properties:
      biodata:
        $ref: '#/definitions/controller.Karyawan'
      checkin:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: MASUK
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: 123.11
        type: number
      phone_number:
        example: "08123456789"
        type: string
    type: object
  controller.Question:
    properties:
      nomor:
        example: 1
        type: integer
      options:
        example: a.Sukarno b.Jokowi
        type: string
      text:
        example: Siapa Presiden pertama Indonesia?
        type: string
    type: object
  controller.Responden:
    properties:
      email:
        example: jasmine@gmail.com
        type: string
      jenis_kelamin:
        example: Prempuan
        type: string
      nama:
        description: ID               primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: Jasmine
        type: string
      phone_number:
        example: "081243284212"
        type: string
      usia:
        example: 18
        type: integer
    type: object
  controller.Survey:
    properties:
      kode:
        example: 101
        type: integer
      soal:
        $ref: '#/definitions/controller.Question'
      title:
        example: Sejarah
        type: string
    type: object
host: jaehyun.herokuapp.com
info:
  contact:
    email: 1214026@std.ulbi.ac.id
    name: API Support
    url: https://github.com/stefanymelda
  description: This is a sample server.
  title: TES SWAG
  version: "1.0"
paths:
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data presensi.
      tags:
      - Presensi
  /deletes/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data survey.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data survey.
      tags:
      - Survey
  /dlt/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data kuesioner.
      tags:
      - Kuesioner
  /ins:
    post:
      consumes:
      - application/json
      description: Input data presensi.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data presensi.
      tags:
      - Presensi
  /ins1:
    post:
      consumes:
      - application/json
      description: Input data kuesioner.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Kuesioner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data kuesioner.
      tags:
      - Kuesioner
  /ins2:
    post:
      consumes:
      - application/json
      description: Input data survey.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Survey'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data survey.
      tags:
      - Survey
  /kuesioner:
    get:
      consumes:
      - application/json
      description: Mengambil semua data kuesioner.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
      summary: Get All Data Kuesioner.
      tags:
      - Kuesioner
  /kuesioner/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Kuesioner.
      tags:
      - Kuesioner
  /presensi:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - Presensi
  /presensi/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Presensi.
      tags:
      - Presensi
  /survey:
    get:
      consumes:
      - application/json
      description: Mengambil semua data survey.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Survey'
      summary: Get All Data Survey.
      tags:
      - Survey
  /survey/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data survey.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Survey'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Survey.
      tags:
      - Survey
  /upd/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Presensi
  /update/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Kuesioner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data kuesioner.
      tags:
      - Kuesioner
  /updatesurvey/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data survey.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Survey'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data survey.
      tags:
      - Survey
schemes:
- https
- http
swagger: "2.0"
