basePath: /
definitions:
  controller.Kuesioner:
    properties:
      biodata:
        $ref: '#/definitions/controller.Responden'
      email:
        example: jasmine@gmail.com
        type: string
      latitude:
        example: 123.11
        type: number
      location:
        example: Bandung
        type: string
      longitude:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: 123.11
        type: number
      status:
        description: Datetime     primitive.DateTime `bson:"datetime,omitempty" json:"datetime,omitempty"`
        example: Done
        type: string
    type: object
  controller.Responden:
    properties:
      email:
        example: jasmine@gmail.com
        type: string
      jenis_kelamin:
        example: Prempuan
        type: string
      nama:
        description: ID               primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: Jasmine
        type: string
      phone_number:
        example: "081243284212"
        type: string
      usia:
        example: 18
        type: integer
    type: object
host: jaehyun.herokuapp.com
info:
  contact:
    email: 1214026@std.ulbi.ac.id
    name: API Support
    url: https://github.com/stefanymelda
  description: This is a sample server.
  title: TES SWAG
  version: "1.0"
paths:
  /dlt/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data kuesioner.
      tags:
      - Kuesioner
  /ins1:
    post:
      consumes:
      - application/json
      description: Input data kuesioner.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Kuesioner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data kuesioner.
      tags:
      - Kuesioner
  /kuesioner:
    get:
      consumes:
      - application/json
      description: Mengambil semua data kuesioner.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
      summary: Get All Data Kuesioner.
      tags:
      - Kuesioner
  /kuesioner/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Kuesioner.
      tags:
      - Kuesioner
  /update/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data kuesioner.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Kuesioner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Kuesioner'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data kuesioner.
      tags:
      - Kuesioner
schemes:
- https
- http
swagger: "2.0"
